name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    if: github.repository_owner == 'psf'
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@89ae32b08ed1a541efecbab17912962a5e38981c # v6.0.2
        with:
            issue-lock-inactive-days: 90
            pr-lock-inactive-days: 90
